import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';

export interface CSIFormData {
  // Project Information
  projectName: string;
  architectName: string;
  contractorName: string;
  requestNumber: string;
  aeProjectNumber?: string;
  specificationSection: string;
  date: Date;

  // Product Information
  specifiedProduct: {
    manufacturer: string;
    tradeName: string;
    modelNumber?: string;
  };

  proposedSubstitution: {
    manufacturer: string;
    tradeName: string;
    modelNumber?: string;
  };

  // Validation Results
  validationStatus: 'APPROVED' | 'EXPERIMENTAL' | 'REJECTED';
  validationScore: number;
  showstopperChecks: {
    astmMatch: boolean;
    fireRatingMatch: boolean;
    compressiveStrengthMatch: boolean;
    tensileStrengthMatch: boolean;
    modulusMatch: boolean;
    rValueMatch: boolean;
    permRatingMatch: boolean;
    stcMatch: boolean;
    iicMatch: boolean;
    ulListingMatch: boolean;
    laborUnitsMatch: boolean;
    lifecycleMatch: boolean;
  };

  // Cost Comparison
  costComparison: {
    specifiedCost: number;
    proposedCost: number;
    netChange: number;
    laborCostDelta?: number;
    lifecycleCostDelta?: number;
  };

  // Environmental Impact
  environmentalImpact: {
    specifiedGWP: number;
    proposedGWP: number;
    gwpReduction: number;
    gwpReductionPercent: number;
    specifiedEPD?: string;
    proposedEPD?: string;
  };

  // Technical Specifications
  technicalSpecs: {
    specified: {
      astmCodes?: string[];
      fireRating?: string;
      compressiveStrength?: number;
      tensileStrength?: number;
      rValue?: number;
      stcRating?: number;
      warranty?: number;
    };
    proposed: {
      astmCodes?: string[];
      fireRating?: string;
      compressiveStrength?: number;
      tensileStrength?: number;
      rValue?: number;
      stcRating?: number;
      warranty?: number;
    };
  };

  // Justification
  reasonForSubstitution: string;
  additionalNotes?: string;
}

const PAGE_W = 612;
const PAGE_H = 792;
const MARGIN = 50;
const COL_W = (PAGE_W - MARGIN * 2) / 3;

function statusColor(status: string): [number, number, number] {
  if (status === 'APPROVED') return [0, 0.6, 0.2];
  if (status === 'EXPERIMENTAL') return [0.85, 0.5, 0];
  return [0.8, 0.1, 0.1];
}

function wrapText(text: string, maxChars: number): string[] {
  const words = text.split(/\s+/);
  const lines: string[] = [];
  let current = '';
  for (const w of words) {
    if ((current + ' ' + w).trim().length > maxChars) {
      if (current) lines.push(current.trim());
      current = w;
    } else {
      current += (current ? ' ' : '') + w;
    }
  }
  if (current) lines.push(current.trim());
  return lines;
}

export class CSIFormGenerator {
  async generate(data: CSIFormData): Promise<Buffer> {
    const pdfDoc = await PDFDocument.create();
    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
    const fontItalic = await pdfDoc.embedFont(StandardFonts.HelveticaOblique);

    const black = rgb(0, 0, 0);
    const gray = rgb(0.4, 0.4, 0.4);
    const green = rgb(0, 0.6, 0.2);
    const red = rgb(0.8, 0.1, 0.1);
    const [sr, sg, sb] = statusColor(data.validationStatus);
    const statusRgb = rgb(sr, sg, sb);

    // ─── PAGE 1: Project Info, Products, Cost, Validation Status ───────────
    const p1 = pdfDoc.addPage([PAGE_W, PAGE_H]);
    let y = PAGE_H - 60;

    const draw = (
      page: typeof p1,
      text: string,
      x: number,
      yPos: number,
      opts: { size?: number; bold?: boolean; italic?: boolean; color?: ReturnType<typeof rgb> } = {}
    ) => {
      page.drawText(text, {
        x,
        y: yPos,
        size: opts.size ?? 10,
        font: opts.bold ? fontBold : opts.italic ? fontItalic : font,
        color: opts.color ?? black,
      });
    };

    const footer = (page: typeof p1) => {
      draw(page, 'Generated by GreenChainz | Verified Sustainable Sourcing', MARGIN, 28, {
        size: 8,
        italic: true,
        color: gray,
      });
      page.drawLine({
        start: { x: MARGIN, y: 38 },
        end: { x: PAGE_W - MARGIN, y: 38 },
        thickness: 0.5,
        color: gray,
      });
    };

    // Header
    draw(p1, 'SUBSTITUTION REQUEST', MARGIN, y, { size: 18, bold: true });
    y -= 20;
    draw(p1, 'CSI Form 13.1A', MARGIN, y, { size: 12 });
    y -= 16;
    draw(p1, '(After the Bidding/Negotiating Phase)', MARGIN, y, { size: 10, color: gray });
    y -= 30;

    // Section: Project Information
    draw(p1, 'Project Information', MARGIN, y, { size: 12, bold: true });
    y -= 18;
    const fields: [string, string][] = [
      ['Project', data.projectName],
      ['To (Architect/Engineer)', data.architectName],
      ['From (Contractor)', data.contractorName],
      ['Date', data.date.toLocaleDateString()],
      ['Substitution Request No.', data.requestNumber],
      ...(data.aeProjectNumber ? [['A/E Project No.', data.aeProjectNumber] as [string, string]] : []),
      ['Specification Section', data.specificationSection],
    ];
    for (const [label, value] of fields) {
      draw(p1, `${label}:`, MARGIN, y, { size: 10, bold: true });
      draw(p1, value, MARGIN + 180, y, { size: 10 });
      y -= 14;
    }

    y -= 14;
    // Section: Products
    draw(p1, 'Product Information', MARGIN, y, { size: 12, bold: true });
    y -= 18;
    draw(p1, 'Specified Product:', MARGIN, y, { size: 10, bold: true });
    y -= 14;
    draw(p1, `  Manufacturer: ${data.specifiedProduct.manufacturer}`, MARGIN, y, { size: 10 });
    y -= 14;
    draw(p1, `  Trade Name: ${data.specifiedProduct.tradeName}`, MARGIN, y, { size: 10 });
    if (data.specifiedProduct.modelNumber) {
      y -= 14;
      draw(p1, `  Model Number: ${data.specifiedProduct.modelNumber}`, MARGIN, y, { size: 10 });
    }
    y -= 20;
    draw(p1, 'Proposed Substitution:', MARGIN, y, { size: 10, bold: true });
    y -= 14;
    draw(p1, `  Manufacturer: ${data.proposedSubstitution.manufacturer}`, MARGIN, y, { size: 10 });
    y -= 14;
    draw(p1, `  Trade Name: ${data.proposedSubstitution.tradeName}`, MARGIN, y, { size: 10 });
    if (data.proposedSubstitution.modelNumber) {
      y -= 14;
      draw(p1, `  Model Number: ${data.proposedSubstitution.modelNumber}`, MARGIN, y, { size: 10 });
    }

    y -= 24;
    // Section: Cost Comparison
    draw(p1, 'Cost Comparison', MARGIN, y, { size: 12, bold: true });
    y -= 18;
    draw(p1, 'Cost of Specified Product:', MARGIN, y, { size: 10, bold: true });
    draw(p1, `$${data.costComparison.specifiedCost.toLocaleString('en-US', { minimumFractionDigits: 2 })}`, MARGIN + 200, y, { size: 10 });
    y -= 14;
    draw(p1, 'Cost of Proposed Substitution:', MARGIN, y, { size: 10, bold: true });
    draw(p1, `$${data.costComparison.proposedCost.toLocaleString('en-US', { minimumFractionDigits: 2 })}`, MARGIN + 200, y, { size: 10 });
    y -= 14;
    draw(p1, 'Net Change in Contract Sum:', MARGIN, y, { size: 10, bold: true });
    const netColor = data.costComparison.netChange < 0 ? green : data.costComparison.netChange > 0 ? red : black;
    const netSign = data.costComparison.netChange >= 0 ? '+' : '';
    draw(p1, `${netSign}$${data.costComparison.netChange.toLocaleString('en-US', { minimumFractionDigits: 2 })}`, MARGIN + 200, y, { size: 10, color: netColor });

    y -= 24;
    // Section: Validation Status
    draw(p1, 'GreenChainz Validation Status', MARGIN, y, { size: 12, bold: true });
    y -= 18;
    draw(p1, 'Status:', MARGIN, y, { size: 10, bold: true });
    draw(p1, data.validationStatus, MARGIN + 60, y, { size: 10, bold: true, color: statusRgb });
    y -= 14;
    draw(p1, 'Validation Score:', MARGIN, y, { size: 10, bold: true });
    draw(p1, `${data.validationScore}/100`, MARGIN + 120, y, { size: 10 });

    footer(p1);

    // ─── PAGE 2: Technical Specs + Showstopper Checks ───────────────────────
    const p2 = pdfDoc.addPage([PAGE_W, PAGE_H]);
    y = PAGE_H - 60;

    draw(p2, 'Technical Specifications Comparison', MARGIN, y, { size: 14, bold: true });
    y -= 30;

    draw(p2, 'Functional Equivalence Validation', MARGIN, y, { size: 12, bold: true });
    y -= 18;

    const checks: [string, boolean][] = [
      ['ASTM Code Match', data.showstopperChecks.astmMatch],
      ['Fire Rating Match', data.showstopperChecks.fireRatingMatch],
      ['Compressive Strength', data.showstopperChecks.compressiveStrengthMatch],
      ['Tensile Strength', data.showstopperChecks.tensileStrengthMatch],
      ['Modulus of Elasticity', data.showstopperChecks.modulusMatch],
      ['R-Value', data.showstopperChecks.rValueMatch],
      ['Perm Rating', data.showstopperChecks.permRatingMatch],
      ['STC Rating', data.showstopperChecks.stcMatch],
      ['IIC Rating', data.showstopperChecks.iicMatch],
      ['UL Listing', data.showstopperChecks.ulListingMatch],
      ['Labor Units', data.showstopperChecks.laborUnitsMatch],
      ['Lifecycle / Warranty', data.showstopperChecks.lifecycleMatch],
    ];

    for (const [label, passed] of checks) {
      draw(p2, `${label}:`, MARGIN, y, { size: 10, bold: true });
      draw(p2, passed ? 'PASS' : 'FAIL', MARGIN + 180, y, { size: 10, bold: true, color: passed ? green : red });
      y -= 14;
    }

    y -= 20;
    draw(p2, 'Detailed Specifications', MARGIN, y, { size: 12, bold: true });
    y -= 18;

    // Table header
    draw(p2, 'Property', MARGIN, y, { size: 9, bold: true });
    draw(p2, 'Specified', MARGIN + COL_W, y, { size: 9, bold: true });
    draw(p2, 'Proposed', MARGIN + COL_W * 2, y, { size: 9, bold: true });
    y -= 14;

    const specs: [string, string, string][] = [
      ['ASTM Codes', data.technicalSpecs.specified.astmCodes?.join(', ') || 'N/A', data.technicalSpecs.proposed.astmCodes?.join(', ') || 'N/A'],
      ['Fire Rating', data.technicalSpecs.specified.fireRating || 'N/A', data.technicalSpecs.proposed.fireRating || 'N/A'],
      ['Compressive Strength (psi)', data.technicalSpecs.specified.compressiveStrength?.toLocaleString() || 'N/A', data.technicalSpecs.proposed.compressiveStrength?.toLocaleString() || 'N/A'],
      ['Tensile Strength (psi)', data.technicalSpecs.specified.tensileStrength?.toLocaleString() || 'N/A', data.technicalSpecs.proposed.tensileStrength?.toLocaleString() || 'N/A'],
      ['R-Value', data.technicalSpecs.specified.rValue?.toString() || 'N/A', data.technicalSpecs.proposed.rValue?.toString() || 'N/A'],
      ['STC Rating', data.technicalSpecs.specified.stcRating?.toString() || 'N/A', data.technicalSpecs.proposed.stcRating?.toString() || 'N/A'],
      ['Warranty (years)', data.technicalSpecs.specified.warranty?.toString() || 'N/A', data.technicalSpecs.proposed.warranty?.toString() || 'N/A'],
    ];

    for (const [prop, specified, proposed] of specs) {
      draw(p2, prop, MARGIN, y, { size: 9 });
      draw(p2, specified, MARGIN + COL_W, y, { size: 9 });
      draw(p2, proposed, MARGIN + COL_W * 2, y, { size: 9 });
      y -= 13;
    }

    footer(p2);

    // ─── PAGE 3: Environmental Impact, Justification, Signatures ────────────
    const p3 = pdfDoc.addPage([PAGE_W, PAGE_H]);
    y = PAGE_H - 60;

    draw(p3, 'Environmental Impact & Sustainability', MARGIN, y, { size: 14, bold: true });
    y -= 30;

    draw(p3, 'Carbon Footprint Comparison (GWP)', MARGIN, y, { size: 12, bold: true });
    y -= 18;
    draw(p3, 'Specified Product GWP:', MARGIN, y, { size: 10, bold: true });
    draw(p3, `${data.environmentalImpact.specifiedGWP.toFixed(2)} kg CO2e`, MARGIN + 180, y, { size: 10 });
    y -= 14;
    draw(p3, 'Proposed Product GWP:', MARGIN, y, { size: 10, bold: true });
    draw(p3, `${data.environmentalImpact.proposedGWP.toFixed(2)} kg CO2e`, MARGIN + 180, y, { size: 10 });
    y -= 14;
    draw(p3, 'GWP Reduction:', MARGIN, y, { size: 10, bold: true });
    const gwpColor = data.environmentalImpact.gwpReduction > 0 ? green : red;
    draw(p3, `${data.environmentalImpact.gwpReduction.toFixed(2)} kg CO2e (${data.environmentalImpact.gwpReductionPercent.toFixed(1)}%)`, MARGIN + 180, y, { size: 10, color: gwpColor });
    if (data.environmentalImpact.specifiedEPD) {
      y -= 14;
      draw(p3, 'Specified EPD:', MARGIN, y, { size: 10, bold: true });
      draw(p3, data.environmentalImpact.specifiedEPD, MARGIN + 180, y, { size: 10 });
    }
    if (data.environmentalImpact.proposedEPD) {
      y -= 14;
      draw(p3, 'Proposed EPD:', MARGIN, y, { size: 10, bold: true });
      draw(p3, data.environmentalImpact.proposedEPD, MARGIN + 180, y, { size: 10 });
    }

    y -= 24;
    draw(p3, 'Reason for Substitution', MARGIN, y, { size: 12, bold: true });
    y -= 16;
    const justLines = wrapText(data.reasonForSubstitution, 90);
    for (const line of justLines) {
      draw(p3, line, MARGIN, y, { size: 10 });
      y -= 13;
    }

    if (data.additionalNotes) {
      y -= 14;
      draw(p3, 'Additional Notes', MARGIN, y, { size: 12, bold: true });
      y -= 16;
      const noteLines = wrapText(data.additionalNotes, 90);
      for (const line of noteLines) {
        draw(p3, line, MARGIN, y, { size: 10 });
        y -= 13;
      }
    }

    y -= 24;
    draw(p3, 'Certification', MARGIN, y, { size: 12, bold: true });
    y -= 16;
    const certText =
      `The undersigned certifies that the proposed substitution has been fully investigated and ` +
      `determined to be ${
        data.validationStatus === 'APPROVED'
          ? 'equal or superior'
          : data.validationStatus === 'EXPERIMENTAL'
          ? 'substantially equivalent with minor differences'
          : 'not equivalent'
      } in all material respects to the specified product. This certification is based on ` +
      `GreenChainz automated validation analysis and supporting technical documentation.`;
    const certLines = wrapText(certText, 90);
    for (const line of certLines) {
      draw(p3, line, MARGIN, y, { size: 9, italic: true });
      y -= 12;
    }

    // Signature blocks
    y -= 30;
    draw(p3, 'Submitted by:', MARGIN, y, { size: 10, bold: true });
    draw(p3, 'Reviewed by:', MARGIN + COL_W + MARGIN, y, { size: 10, bold: true });
    y -= 24;
    p3.drawLine({ start: { x: MARGIN, y }, end: { x: MARGIN + COL_W - 20, y }, thickness: 0.75, color: black });
    p3.drawLine({ start: { x: MARGIN + COL_W + MARGIN, y }, end: { x: PAGE_W - MARGIN, y }, thickness: 0.75, color: black });
    y -= 13;
    draw(p3, '(Contractor Signature)', MARGIN, y, { size: 9, color: gray });
    draw(p3, '(Architect Signature)', MARGIN + COL_W + MARGIN, y, { size: 9, color: gray });
    y -= 20;
    draw(p3, 'Date: _______________', MARGIN, y, { size: 9 });
    draw(p3, 'Date: _______________', MARGIN + COL_W + MARGIN, y, { size: 9 });

    footer(p3);

    const pdfBytes = await pdfDoc.save();
    return Buffer.from(pdfBytes);
  }
}
