/**
 * Swap Validation Router
 *
 * tRPC procedures for validating material substitutions
 */

import { z } from 'zod';
import { publicProcedure, router } from '../_core/trpc';
import { validateSwap, type MaterialTechnicalSpecs } from '../services/swapValidationService';
import { getDb } from '../db';
import { materialTechnicalSpecs, swapValidations, materials } from '../../drizzle/schema';
import { eq, and, desc } from 'drizzle-orm';

// ─── CSI Form Generator ──────────────────────────────────────────────────────

function buildCsiMarkdown(params: {
  validation: typeof swapValidations.$inferSelect;
  incumbent: typeof materials.$inferSelect;
  sustainable: typeof materials.$inferSelect;
  projectName?: string;
  specSection?: string;
}): string {
  const { validation, incumbent, sustainable, projectName, specSection } = params;
  const now = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  const section = specSection ?? '01 81 13';
  const costDelta = validation.costDeltaPercentage ? `${parseFloat(validation.costDeltaPercentage as string).toFixed(1)}%` : 'N/A';
  const carbonReduction = validation.carbonReductionPercentage ? `${parseFloat(validation.carbonReductionPercentage as string).toFixed(1)}%` : 'N/A';
  const score = parseFloat(validation.overallScore as string).toFixed(1);

  return [
    `# MATERIAL SUBSTITUTION REQUEST`,
    `## CSI Section ${section} — Sustainable Design Requirements`,
    ``,
    `**Date:** ${now}`,
    `**Project:** ${projectName ?? 'Unspecified'}`,
    `**Validation ID:** GCZ-${validation.id}`,
    `**Status:** ${validation.validationStatus}`,
    `**Overall Score:** ${score}/100`,
    ``,
    `---`,
    ``,
    `## PART 1 — GENERAL`,
    ``,
    `### 1.01 SUMMARY`,
    ``,
    `This document certifies the results of a GreenChainz AI-assisted material substitution`,
    `validation conducted in accordance with CSI MasterFormat Division 01 requirements.`,
    `The proposed substitution has been evaluated across structural performance, fire safety,`,
    `thermal performance, acoustic performance, supply chain reliability, and cost impact.`,
    ``,
    `### 1.02 INCUMBENT MATERIAL`,
    ``,
    `| Field | Value |`,
    `|-------|-------|`,
    `| Material Name | ${incumbent.name} |`,
    `| Product Name | ${incumbent.productName ?? '—'} |`,
    `| Category | ${incumbent.category} |`,
    `| EPD Number | ${incumbent.epdNumber ?? '—'} |`,
    `| GWP Value | ${incumbent.gwpValue ?? '—'} ${incumbent.gwpUnit ?? ''} |`,
    `| Compliance Grade | ${incumbent.complianceGrade ?? '—'} |`,
    `| US Manufactured | ${incumbent.usManufactured ? 'Yes' : 'No'} |`,
    ``,
    `### 1.03 PROPOSED SUSTAINABLE SUBSTITUTE`,
    ``,
    `| Field | Value |`,
    `|-------|-------|`,
    `| Material Name | ${sustainable.name} |`,
    `| Product Name | ${sustainable.productName ?? '—'} |`,
    `| Category | ${sustainable.category} |`,
    `| EPD Number | ${sustainable.epdNumber ?? '—'} |`,
    `| EPD URL | ${sustainable.epdUrl ?? '—'} |`,
    `| GWP Value | ${sustainable.gwpValue ?? '—'} ${sustainable.gwpUnit ?? ''} |`,
    `| Compliance Grade | ${sustainable.complianceGrade ?? '—'} |`,
    `| US Manufactured | ${sustainable.usManufactured ? 'Yes' : 'No'} |`,
    `| Has EPD | ${sustainable.hasEpd ? 'Yes' : 'No'} |`,
    `| Has HPD | ${sustainable.hasHpd ? 'Yes' : 'No'} |`,
    `| GREENGUARD Certified | ${sustainable.hasGreenguard ? 'Yes' : 'No'} |`,
    `| On Red List | ${sustainable.onRedList ? '⚠️ Yes' : 'No'} |`,
    ``,
    `---`,
    ``,
    `## PART 2 — VALIDATION RESULTS`,
    ``,
    `### 2.01 SHOWSTOPPER CHECK SUMMARY`,
    ``,
    `| Metric | Result |`,
    `|--------|--------|`,
    `| Passed Checks | ${validation.passedChecks} |`,
    `| Failed Checks | ${validation.failedChecks} |`,
    `| Skipped Checks | ${validation.skippedChecks} |`,
    `| Overall Score | ${score}/100 |`,
    `| Validation Status | **${validation.validationStatus}** |`,
    ``,
    `### 2.02 COST IMPACT`,
    ``,
    `| Metric | Value |`,
    `|--------|-------|`,
    `| Incumbent Total Cost | $${validation.incumbentTotalCost ?? 'N/A'} |`,
    `| Sustainable Total Cost | $${validation.sustainableTotalCost ?? 'N/A'} |`,
    `| Cost Delta | ${costDelta} |`,
    ``,
    `### 2.03 CARBON IMPACT`,
    ``,
    `| Metric | Value |`,
    `|--------|-------|`,
    `| Incumbent GWP | ${validation.incumbentGwp ?? 'N/A'} kg CO₂e |`,
    `| Sustainable GWP | ${validation.sustainableGwp ?? 'N/A'} kg CO₂e |`,
    `| Carbon Reduction | ${carbonReduction} |`,
    ``,
    `---`,
    ``,
    `## PART 3 — RECOMMENDATION`,
    ``,
    `${validation.recommendation}`,
    ``,
    `---`,
    ``,
    `## PART 4 — CERTIFICATION`,
    ``,
    `This substitution analysis was generated by the GreenChainz AI Validation Engine.`,
    `Results are valid for 180 days from the validation date.`,
    ``,
    `**Validated:** ${new Date(validation.validatedAt).toLocaleDateString('en-US')}`,
    `**Expires:** ${validation.expiresAt ? new Date(validation.expiresAt).toLocaleDateString('en-US') : 'N/A'}`,
    `**Reference:** GCZ-${validation.id}`,
    ``,
    `*Powered by GreenChainz · greenchainz.com*`,
  ].join('\n');
}

// ─── Router ──────────────────────────────────────────────────────────────────

export const swapValidationRouter = router({
  /**
   * Validate a material swap
   * Compares incumbent and sustainable materials across all showstopper checks
   */
  validateMaterialSwap: publicProcedure
    .input(z.object({
      incumbentMaterialId: z.number(),
      sustainableMaterialId: z.number(),
      projectId: z.number().optional(),
      saveResult: z.boolean().default(true),
    }))
    .mutation(async ({ input }) => {
      const db = await getDb();

      const [incumbentSpecs, sustainableSpecs] = await Promise.all([
        db.select().from(materialTechnicalSpecs)
          .where(eq(materialTechnicalSpecs.materialId, input.incumbentMaterialId))
          .limit(1),
        db.select().from(materialTechnicalSpecs)
          .where(eq(materialTechnicalSpecs.materialId, input.sustainableMaterialId))
          .limit(1),
      ]);

      if (incumbentSpecs.length === 0) {
        throw new Error(`No technical specs found for incumbent material ID ${input.incumbentMaterialId}`);
      }
      if (sustainableSpecs.length === 0) {
        throw new Error(`No technical specs found for sustainable material ID ${input.sustainableMaterialId}`);
      }

      const validationResult = validateSwap(incumbentSpecs[0], sustainableSpecs[0]);

      if (input.saveResult) {
        const insertData = {
          incumbentMaterialId: input.incumbentMaterialId,
          sustainableMaterialId: input.sustainableMaterialId,
          projectId: input.projectId || null,
          validationStatus: validationResult.validationStatus,
          overallScore: validationResult.overallScore.toString(),
          showstopperResults: validationResult.showstopperResults as any,
          failedChecks: validationResult.failedChecks,
          passedChecks: validationResult.passedChecks,
          skippedChecks: validationResult.skippedChecks,
          recommendation: validationResult.recommendation,
          validatedAt: new Date(),
          expiresAt: new Date(Date.now() + 180 * 24 * 60 * 60 * 1000),
        };

        const [savedValidation] = await db.insert(swapValidations)
          .values(insertData)
          .$returningId();

        return { ...validationResult, validationId: savedValidation.id };
      }

      return validationResult;
    }),

  /**
   * Get validation history
   */
  getValidationHistory: publicProcedure
    .input(z.object({
      incumbentMaterialId: z.number().optional(),
      sustainableMaterialId: z.number().optional(),
      projectId: z.number().optional(),
      validationStatus: z.enum(['APPROVED', 'EXPERIMENTAL', 'REJECTED']).optional(),
      limit: z.number().default(50),
    }))
    .query(async ({ input }) => {
      const db = await getDb();

      let query = db.select().from(swapValidations);

      const conditions: any[] = [];
      if (input.incumbentMaterialId) conditions.push(eq(swapValidations.incumbentMaterialId, input.incumbentMaterialId));
      if (input.sustainableMaterialId) conditions.push(eq(swapValidations.sustainableMaterialId, input.sustainableMaterialId));
      if (input.projectId) conditions.push(eq(swapValidations.projectId, input.projectId));
      if (input.validationStatus) conditions.push(eq(swapValidations.validationStatus, input.validationStatus));

      if (conditions.length > 0) query = query.where(and(...conditions)) as any;

      const results = await query
        .orderBy(desc(swapValidations.validatedAt))
        .limit(input.limit);

      return results.map(r => ({
        ...r,
        showstopperResults: JSON.parse(r.showstopperResults as string),
      }));
    }),

  /**
   * Get validation by ID
   */
  getValidationById: publicProcedure
    .input(z.object({ validationId: z.number() }))
    .query(async ({ input }) => {
      const db = await getDb();

      const [validation] = await db.select().from(swapValidations)
        .where(eq(swapValidations.id, input.validationId))
        .limit(1);

      if (!validation) throw new Error(`Validation ID ${input.validationId} not found`);

      const [incumbent, sustainable] = await Promise.all([
        db.select().from(materials).where(eq(materials.id, validation.incumbentMaterialId)).limit(1),
        db.select().from(materials).where(eq(materials.id, validation.sustainableMaterialId)).limit(1),
      ]);

      return {
        ...validation,
        showstopperResults: JSON.parse(validation.showstopperResults as string),
        incumbentMaterial: incumbent[0] || null,
        sustainableMaterial: sustainable[0] || null,
      };
    }),

  /**
   * Revalidate a swap
   */
  revalidateSwap: publicProcedure
    .input(z.object({ validationId: z.number() }))
    .mutation(async ({ input }) => {
      const db = await getDb();

      const [existingValidation] = await db.select().from(swapValidations)
        .where(eq(swapValidations.id, input.validationId))
        .limit(1);

      if (!existingValidation) throw new Error(`Validation ID ${input.validationId} not found`);

      const [incumbentSpecs, sustainableSpecs] = await Promise.all([
        db.select().from(materialTechnicalSpecs).where(eq(materialTechnicalSpecs.materialId, existingValidation.incumbentMaterialId)).limit(1),
        db.select().from(materialTechnicalSpecs).where(eq(materialTechnicalSpecs.materialId, existingValidation.sustainableMaterialId)).limit(1),
      ]);

      if (incumbentSpecs.length === 0 || sustainableSpecs.length === 0) {
        throw new Error('Technical specs not found for one or both materials');
      }

      const validationResult = validateSwap(incumbentSpecs[0], sustainableSpecs[0]);

      await db.update(swapValidations)
        .set({
          validationStatus: validationResult.validationStatus,
          overallScore: validationResult.overallScore.toString(),
          showstopperResults: validationResult.showstopperResults as any,
          failedChecks: validationResult.failedChecks,
          passedChecks: validationResult.passedChecks,
          skippedChecks: validationResult.skippedChecks,
          recommendation: validationResult.recommendation,
          validatedAt: new Date(),
          expiresAt: new Date(Date.now() + 180 * 24 * 60 * 60 * 1000),
        })
        .where(eq(swapValidations.id, input.validationId));

      return { ...validationResult, validationId: input.validationId };
    }),

  /**
   * Get validation statistics
   */
  getValidationStats: publicProcedure
    .query(async () => {
      const db = await getDb();

      const allValidations = await db.select().from(swapValidations);

      return {
        total: allValidations.length,
        approved: allValidations.filter(v => v.validationStatus === 'APPROVED').length,
        experimental: allValidations.filter(v => v.validationStatus === 'EXPERIMENTAL').length,
        rejected: allValidations.filter(v => v.validationStatus === 'REJECTED').length,
        averageScore: allValidations.length > 0
          ? allValidations.reduce((sum, v) => sum + parseFloat(v.overallScore as any), 0) / allValidations.length
          : 0,
        recentValidations: allValidations
          .sort((a, b) => new Date(b.validatedAt).getTime() - new Date(a.validatedAt).getTime())
          .slice(0, 10),
      };
    }),

  /**
   * Generate CSI substitution form
   * Returns Markdown text and updates csiFormUrl + csiFormGeneratedAt on the record.
   * The caller (frontend) is responsible for rendering/downloading the Markdown.
   */
  generateCsiForm: publicProcedure
    .input(z.object({
      validationId: z.number(),
      projectName: z.string().optional(),
      specSection: z.string().optional(), // e.g. "01 81 13" — defaults to that if omitted
    }))
    .mutation(async ({ input }) => {
      const db = await getDb();

      // Load validation record
      const [validation] = await db.select().from(swapValidations)
        .where(eq(swapValidations.id, input.validationId))
        .limit(1);

      if (!validation) throw new Error(`Validation ID ${input.validationId} not found`);

      // Load both materials
      const [incumbentRows, sustainableRows] = await Promise.all([
        db.select().from(materials).where(eq(materials.id, validation.incumbentMaterialId)).limit(1),
        db.select().from(materials).where(eq(materials.id, validation.sustainableMaterialId)).limit(1),
      ]);

      if (!incumbentRows[0]) throw new Error(`Incumbent material ID ${validation.incumbentMaterialId} not found`);
      if (!sustainableRows[0]) throw new Error(`Sustainable material ID ${validation.sustainableMaterialId} not found`);

      const markdown = buildCsiMarkdown({
        validation,
        incumbent: incumbentRows[0],
        sustainable: sustainableRows[0],
        projectName: input.projectName,
        specSection: input.specSection,
      });

      // Stamp the record so we know a CSI form was generated
      const generatedAt = new Date();
      const csiRef = `GCZ-${validation.id}-CSI`;

      await db.update(swapValidations)
        .set({
          csiFormUrl: csiRef,
          csiFormGeneratedAt: generatedAt,
          updatedAt: generatedAt,
        })
        .where(eq(swapValidations.id, input.validationId));

      return {
        validationId: input.validationId,
        csiRef,
        generatedAt: generatedAt.toISOString(),
        markdown,
        incumbentName: incumbentRows[0].name,
        sustainableName: sustainableRows[0].name,
        validationStatus: validation.validationStatus,
        overallScore: parseFloat(validation.overallScore as string),
      };
    }),
});
