CREATE TABLE `material_specs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`materialId` int NOT NULL,
	`supplierId` int NOT NULL,
	`submittedBy` int NOT NULL,
	`status` enum('pending','approved','rejected') NOT NULL DEFAULT 'pending',
	`fireRating` varchar(50),
	`fireRatingStandard` varchar(100),
	`rValue` decimal(8,2),
	`thermalUValue` decimal(8,4),
	`compressiveStrength` varchar(100),
	`tensileStrength` varchar(100),
	`astmStandards` text,
	`meetsTitle24` tinyint DEFAULT 0,
	`meetsIecc` tinyint DEFAULT 0,
	`buildingCodes` text,
	`pricePerUnit` decimal(10,2),
	`priceUnit` varchar(50),
	`minimumOrderQuantity` int,
	`moqUnit` varchar(50),
	`bulkDiscountAvailable` tinyint DEFAULT 0,
	`leadTimeDays` int,
	`manufacturingLocation` varchar(255),
	`usManufactured` tinyint DEFAULT 0,
	`regionalAvailabilityMiles` int,
	`shippingRegions` text,
	`inStock` tinyint DEFAULT 1,
	`stockQuantity` int,
	`vocLevel` varchar(50),
	`vocCertification` varchar(100),
	`onRedList` tinyint DEFAULT 0,
	`toxicityRating` varchar(50),
	`indoorAirQualityRating` varchar(50),
	`hasEpd` tinyint DEFAULT 0,
	`hasHpd` tinyint DEFAULT 0,
	`hasFsc` tinyint DEFAULT 0,
	`hasC2c` tinyint DEFAULT 0,
	`hasGreenguard` tinyint DEFAULT 0,
	`hasDeclare` tinyint DEFAULT 0,
	`certificationUrls` text,
	`datasheetUrl` text,
	`specSheetUrl` text,
	`testReportUrls` text,
	`notes` text,
	`recycledContentPct` decimal(5,2),
	`warrantyYears` int,
	`expectedLifecycleYears` int,
	`reviewedBy` int,
	`reviewedAt` timestamp,
	`rejectionReason` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `material_specs_id` PRIMARY KEY(`id`)
);
