export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  ec3ApiKey: process.env.EC3_API_KEY ?? "",
  ec3ClientId: process.env.EC3_CLIENT_ID ?? "",
  ec3ClientSecret: process.env.EC3_CLIENT_SECRET ?? "",
  ec3Username: process.env.EC3_USERNAME ?? "",
  ec3Password: process.env.EC3_PASSWORD ?? "",
};
